#!/usr/bin/env python
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2006-present William Schoenell <wschoenell@gmail.com>

import sys

from chimera.cli.cli import ChimeraCLI, action

# from chimera.core.compat import freeze_support
from chimera.interfaces.pointverify import CanSetScopeButNotThisField, CantSetScopeException
from chimera_pverify.util.astrometrynet import NoSolutionAstrometryNetException
from chimera_pverify.util.astrometrynet import AstrometryNet


class ChimeraPointVerify(ChimeraCLI):
    def __init__(self):
        # are these entities being created or am I referring to existing things?
        # the first entry is how the script will be called
        # the second entry is an English language description of the script
        ChimeraCLI.__init__(self, "chimera-pverify", "Point Verifier", 0.1)
        self.add_help_group("PVERIFY", "PVerify")
        self.add_controller(
            name="pverify",
            cls="PointVerify",
            required=True,
            help_group="PVERIFY",
            help="Pointing verification controller to be used",
        )
        # self.add_parameters(
        #     dict(name="pverify_file", long="fname", type="string", help_group="PVERIFY", help="Does astrometry on file",
        #          metavar="FILE"))

        # self.add_parameters(
        #     dict(
        #         name="nfields",
        #         int="nfields",
        #         type="int",
        #         help_group="PVERIFY",
        #         help="Number of fields to verify",
        #         default=1,
        #     )
        # )
        # self.add_parameters(dict(name="binning", help="Use binning to expose", help_group="PVERIFY"))

    # ok, looks like action establishes that the following method is some
    # action performed by this script
    # @action(int="choose",
    #         help="Chooses a field to point the scope to, moves the scope, takes an image and verifies the pointing",
    #         helpGroup="PVERIFY")
    def check_pointing(self, options):
        """
        Chooses a field to point the scope to, moves the scope,
        takes an image and verifies the pointing
        """
        self.out("Choosing a field in the sky, moving scope and taking images")
        for i_field in range(options.nfields):
            try:
                self.pverify.set_current_field(i_field)
                self.pverify.check_pointing()
            # what is this e for ???
            except CantSetScopeException:
                self.exit("Can't set scope")
            input(f"Field {i_field:d} OK. Press ENTER for next...")

    # @action(int="file",
    #         type="string",
    #         help="Does astrometry on file",
    #         helpGroup="PVERIFY")
    # def file(self, options):
    #     """
    #     Returns a new image with new WCS
    #     """
    #     self.out(f"Doing astrometry on file : {options.file}\n")
    #     try:
    #         AstrometryNet.solve_field(options.file, find_star_method="sex")
    #     except NoSolutionAstrometryNetException:
    #         try:
    #             AstrometryNet.solve_field(
    #                 options.file, find_star_method="astrometry.net")
    #         except NoSolutionAstrometryNetException:
    #             self.exit("Can't set scope")
    #     self.out("OK")
    @action(
        short="H",
        long="--here",
        help="Takes an image where telescope is pointed to, tries to find image RA, DEC, and tries to recenter the telescope",
        help_group="PVERIFY",
    )
    # @action(int="here",
    def check_here(self, options):
        """
        Takes an image where telescope is pointed to,
        tries to find image RA, DEC,
        and tries to recenter the telescope
        """

        # # Check binning

        # if options.binning:
        #     binnings = self.pverify.get_cam().get_binnings()
        #     if options.binning not in list(binnings.keys()):
        #         self.exit("Invalid binning mode. See chimera-cam --info for available binning modes")
        #     imageRequest = dict(binning=options.binning)
        # else:
        image_request = dict()

        self.out("Centering scope on current field")
        try:
            self.pverify.ntrials = 0
            self.pverify.point_verify(image_request)
        except CanSetScopeButNotThisField:
            self.out(
                "The scope has been set on a standard field but it is impossible to set on this - either spotty clouds or too faint stars"
            )
        self.out("OK")


def main():
    cli = ChimeraPointVerify()
    cli.run(sys.argv)
    cli.wait()


if __name__ == "__main__":
    # freeze_support()
    main()
